/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "secondary-fixed-dim": "#ffb77d",
          "on-secondary": "#4d2600",
          "outline": "#859398",
          "primary-fixed": "#b4ebff",
          "on-tertiary-fixed-variant": "#930014",
          "on-secondary-fixed": "#2f1500",
          "secondary-fixed": "#ffdcc3",
          "surface-container": "#1e2023",
          "on-error-container": "#ffdad6",
          "tertiary-container": "#ffaea8",
          "surface-container-highest": "#333538",
          "primary-fixed-dim": "#3cd7ff",
          "on-primary": "#003642",
          "on-secondary-container": "#603100",
          "on-secondary-fixed-variant": "#6e3900",
          "on-tertiary-fixed": "#410004",
          "surface-container-low": "#1a1c1f",
          "on-tertiary-container": "#a40017",
          "surface-bright": "#37393d",
          "surface": "#111316",
          "background": "#111316",
          "error-container": "#93000a",
          "outline-variant": "#3c494e",
          "surface-container-lowest": "#0c0e11",
          "on-primary-fixed": "#001f27",
          "tertiary-fixed": "#ffdad7",
          "inverse-on-surface": "#2f3034",
          "on-primary-fixed-variant": "#004e5f",
          "surface-container-high": "#282a2d",
          "on-background": "#e2e2e6",
          "inverse-primary": "#00677e",
          "on-primary-container": "#00586b",
          "on-error": "#690005",
          "inverse-surface": "#e2e2e6",
          "secondary": "#ffb77d",
          "surface-variant": "#333538",
          "surface-tint": "#3cd7ff",
          "secondary-container": "#fd8b00",
          "primary-container": "#00d4ff",
          "on-tertiary": "#68000b",
          "error": "#ffb4ab",
          "surface-dim": "#111316",
          "tertiary": "#ffd5d1",
          "primary": "#a8e8ff",
          "on-surface": "#e2e2e6",
          "tertiary-fixed-dim": "#ffb3ae",
          "on-surface-variant": "#bbc9cf"
      },
      "fontFamily": {
          "headline": ["Space Grotesk", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Space Grotesk", "sans-serif"],
          "mono": ["Doto", "monospace"]
      }
    },
  },
  plugins: [],
}
